### ISSUE TITLE
Improve example usage

### ISSUE THREAD

**Issue by bradgreens** [n8io/fantasydata-api#10]
Your example usage shows the following code block to pull in and execute the code.

```
var fantasyData = require('fantasydata-api')(options);

var season = '2014REG';
fantasyData.nfl.Byes(season, function(err, results){
  console.log(JSON.stringify(results, null, 2));
});
```

However, in my case at least, I needed to call the `new` operator on the factory returned by the `require` statement. e.g.

```
var fantasyDataFactory = require('fantasydata-api')

var fantasyData = new fantasyDataFactory({
  nfl: {
    version: 'nfl/v2',
    key: 'f7007c6b55724843918f4752cbe8a3a8' // <-- Pass in your nfl key here
  },
})

var season = '2014REG';

fantasyData.nfl.byes(season, function(err, results){
  console.log(JSON.stringify(results, null, 2));
});
```

Also note there was a typo with the property `Byes` -> `byes`.

With that said, do you guys have a strategy for testing this on localhost? I'm seeing CORS request issues so I cannot receive the data yet. Recommendations?

**Comment by bradgreens** [comment]
Looks to me like this library *might* not be including the `Ocp-Apim-Subscription-Key: ••••••••••••••••••••••••••••••••` header?

**Comment by n8io** [comment]
There is a lot that I have yet to add and am looking to the open source community to submit any and all PRs. My current available time outside work hours is severely limited these days.

**Comment by bradgreens** [comment]
No worries, I contacted the Fantasy Data guys and they indicated that browser requests should be JSONP. I tried out `[browser-jsonp](https://www.npmjs.com/package/browser-jsonp)` and was able to retrieve the data.

I'm working on a hobby project with this and if I can contribute I'll be sure to add a PR if it fits.

**Comment by n8io** [comment]
Excellent. Thanks for the JSONP info.
